# Generated by Django 6.1 on 2026-08-24 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название категории:', max_length=60, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название задачи:', max_length=200, verbose_name='Задача')),
                ('description', models.TextField(help_text='Введите описание задачи:', max_length=200, verbose_name='Описание')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Введите дату создания задачи:', verbose_name='Дата создания задачи:')),
                ('due_date', models.DateTimeField(blank=True, help_text='Введите срок выполнения задачи:', null=True, verbose_name='Срок выполнения задачи:')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('category_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='todoapp.category', verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['is_completed', '-created_date'],
            },
        ),
    ]
